INSERT INTO COMPANIES(ID,ADDRESS,VAT_NUMBER) VALUES (1,'Rue Xavier De Bue 54 1180 Uccle',431150351);
INSERT INTO COMPANIES(ID,ADDRESS,VAT_NUMBER) VALUES (2,'Houba de Strooperlaan 96 1090 Jette',531666350);
INSERT INTO COMPANIES(ID,ADDRESS,VAT_NUMBER) VALUES (3,'Rue de la Longue Haie 51 1050 Ixelles',738883516);
INSERT INTO COMPANIES(ID,ADDRESS,VAT_NUMBER) VALUES (4,'Rue de la Suie 51 1060 Saint-Gilles',838659517);

INSERT INTO EMPLOYEES(ID,ADDRESS,FIRST_NAME,LAST_NAME,VAT_NUMBER) VALUES (1,'Rue des Chapeliers 6 1000 Bruxelles','Anakin','Skywalker',null);
INSERT INTO EMPLOYEES(ID,ADDRESS,FIRST_NAME,LAST_NAME,VAT_NUMBER) VALUES (2,'Rue de la Reforme 22 4020 Liège','Han','Solo',469859517);
INSERT INTO EMPLOYEES(ID,ADDRESS,FIRST_NAME,LAST_NAME,VAT_NUMBER) VALUES (3,'Parvis Sainte-Alix 32 1160 Woluwe','Leia','Skywalker',null);
INSERT INTO EMPLOYEES(ID,ADDRESS,FIRST_NAME,LAST_NAME,VAT_NUMBER) VALUES (4,'Rue des Princes 16 1070 Anderlecht','Jena','Lewis',958759517);

INSERT INTO COMPANIES_EMPLOYEES(COMPANIES_ID,EMPLOYEES_ID) VALUES (1,2);
INSERT INTO COMPANIES_EMPLOYEES(COMPANIES_ID,EMPLOYEES_ID) VALUES (1,3);
INSERT INTO COMPANIES_EMPLOYEES(COMPANIES_ID,EMPLOYEES_ID) VALUES (2,2);
INSERT INTO COMPANIES_EMPLOYEES(COMPANIES_ID,EMPLOYEES_ID) VALUES (2,4);
INSERT INTO COMPANIES_EMPLOYEES(COMPANIES_ID,EMPLOYEES_ID) VALUES (3,4);

      
